spring:
  application:
    name: configserver
  profiles:
    active: test
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: file:///c:\Temp\configserver\ecom-microservices\configserver\src\main\resources\config
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sipopesc/ecomm-app-config
          default-label: master
          username: ${GIT_USER}
          password: ${GIT_TOKEN}
#  profiles:
#    active: jdbc
#  datasource:
#    url: jdbc:mysql://localhost:3306/configdb
#    username: ${USER}
#    password: ${PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    config:
#      server:
#        jdbc:
#          sql: "SELECT PROP_KEY, PROP_VALUE from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?"
#          default-label: main
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
server:
  port: 8888

#encrypt:
#  key: "0E329232EA6D0D73"

#encrypt:
#  key-store:
#    location: config-server.jks
#    password: mypass
#    alias: config-server-key