spring:
  application:
    name: configserver
  profiles:
    active: native
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:guest}
    connection-timeout: 30000
  cloud:
    config:
      server:
        native:
          search-locations: file:///c:\Temp\configserver\ecom-microservices\configserver\src\main\resources\config\

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"